
------------------------------ERROR------------------------------
15/02/2022 12:02:05 - UnableToWorkException: I’m not hired yet, lol
Traceback (most recent call last):
  File "F:\IT\MyScripts\oop\app.py", line 26, in <module>
    main()
  File "F:\IT\MyScripts\oop\app.py", line 21, in main
    cand3.work()
  File "F:\IT\MyScripts\oop\models.py", line 163, in __getattr__
    raise UnableToWorkException('I’m not hired yet, lol')
models.UnableToWorkException: I’m not hired yet, lol
